baseURL = 'https://vimacs.app/'
languageCode = 'en-us'
title = 'Vimacs.app'
copyright = 'Ryan "sandbox" Wilcox'
[params]
author = 'sandbox'
subtitle = 'Emacs config for the Neovim neophyte wanting more'
images = ['/screenshots/2023-12-09T224513Z.png', '/screenshots/2023-12-09T224553Z.png', '/screenshots/2023-12-09T224736Z.png', '/screenshots/2023-12-09T224827Z.png', '/screenshots/2023-12-09T224858Z.png', '/screenshots/2023-12-09T224958Z.png']
