baseURL = 'https://vimacs.app/'
languageCode = 'en-us'
title = 'Vimacs.app'
copyright = 'Ryan "sandbox" Wilcox'
[params]
author = 'sandbox'
subtitle = 'Emacs config for the Neovim neophyte wanting more'
images = ['/screenshots/2023-12-06T005831Z.png', '/screenshots/2023-12-06T005708Z.png', '/screenshots/2023-12-06T005612Z.png', '/screenshots/2023-12-06T005536Z.png']
